version: '3.9'
services:
  app:
    build:
      target: base
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app:cached
    ports:
      - '3000:3000'
